//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OzetAPP.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OzetAppDBEntities2 : DbContext
    {
        public OzetAppDBEntities2()
            : base("name=OzetAppDBEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tbl_haneler> tbl_haneler { get; set; }
        public virtual DbSet<tbl_islemler> tbl_islemler { get; set; }
        public virtual DbSet<tbl_kategoriler> tbl_kategoriler { get; set; }
        public virtual DbSet<tbl_kullanicilar> tbl_kullanicilar { get; set; }
    }
}
