//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OzetAPP.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_haneler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_haneler()
        {
            this.tbl_islemler = new HashSet<tbl_islemler>();
            this.tbl_kullanicilar = new HashSet<tbl_kullanicilar>();
        }
    
        public int hane_id { get; set; }
        public string hane_kod { get; set; }
        public Nullable<bool> hane_durum { get; set; }
        public Nullable<decimal> hane_bakiye { get; set; }
        public Nullable<int> hane_sahip { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_islemler> tbl_islemler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_kullanicilar> tbl_kullanicilar { get; set; }
        public virtual tbl_kullanicilar tbl_kullanicilar1 { get; set; }
    }
}
