//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OzetAPP.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tbl_kullanicilar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_kullanicilar()
        {
            this.tbl_islemler = new HashSet<tbl_islemler>();
            this.tbl_kategoriler = new HashSet<tbl_kategoriler>();
            this.tbl_haneler1 = new HashSet<tbl_haneler>();
        }
    
        public int kullanici_id { get; set; }
        [Required(ErrorMessage = "Bu Alan Boþ Býrakýlamaz")]
        [MinLength(3, ErrorMessage = "Kullanýcý Adý 3 Karakterden Uzun Olmalýdýr")]
        [MaxLength(100, ErrorMessage = "Kullanýcý Adý 100 Karakterden Fazla Olamaz")]
        public string kullanici_ad { get; set; }

        [Required(ErrorMessage = "Bu Alan Boþ Býrakýlamaz")]
        [MinLength(3, ErrorMessage = "Ýsim 3 Karakterden Uzun Olmalýdýr")]
        [MaxLength(100, ErrorMessage = "Ýsim 100 Karakterden Fazla Olamaz")]
        public string kullanici_isim { get; set; }

        [Required(ErrorMessage = "Bu Alan Boþ Býrakýlamaz")]
        public string kullanici_sifre { get; set; }

        public string kullanici_sifretekrar { get; set; }
        public Nullable<int> kullanici_hane { get; set; }
        public string kullanici_fotograf { get; set; }
        public Nullable<decimal> kullanici_bakiye { get; set; }
    
        public virtual tbl_haneler tbl_haneler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_islemler> tbl_islemler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_kategoriler> tbl_kategoriler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_haneler> tbl_haneler1 { get; set; }
    }
}
